services:
  electrs:
    build:
      context: .
      dockerfile: Dockerfile.electrs
    container_name: electrs
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./electrs:/home/electrs/.electrs
    ports:
      - ${ELECTRS_PORT}:50001
      - ${ESPLORA_PORT}:3000
    command:
      [
        "./electrs",
        "--daemon-rpc-addr", "${BITCOIN_RPC_URL}",
        "--electrum-rpc-addr", "0.0.0.0:50001",
        "--http-addr", "0.0.0.0:3000",
        "--db-dir", "/home/electrs/.electrs/db",
        "--cookie", "${RPC_USER}:${RPC_PASS}",
        "--lightmode",
        "--jsonrpc-import",
        "--utxos-limit", "1000000",
        "-vvvv"
      ]
