FROM rust:1.87.0-bookworm as builder

RUN apt update
RUN apt install -y git pkg-config libssl-dev

WORKDIR /root

RUN git clone https://github.com/ordinals/ord.git

WORKDIR /root/ord

RUN git checkout 0.23.1

RUN cargo build --release

FROM debian:12.10-slim

RUN apt update && apt install -y libssl-dev

WORKDIR /root/ord

COPY --from=builder /root/ord/target/release/ord .

ENV RUST_BACKTRACE=1
ENV RUST_LOG=debug
