FROM debian:12.10-slim

RUN apt update
RUN apt install -y git build-essential cmake pkgconf python3 libevent-dev libboost-dev libsqlite3-dev libzmq3-dev systemtap-sdt-dev

WORKDIR /root

RUN git clone https://github.com/bitcoin/bitcoin.git

WORKDIR /root/bitcoin

RUN git checkout v29.0

RUN cmake -B build
RUN cmake --build build

WORKDIR /root/bitcoin/build/bin
